// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjMahvKt4NNSqSQ2vWgl3JM4lWkhCAhZI',
    appId: '1:879415072254:web:cd022022514f0ae8495caf',
    messagingSenderId: '879415072254',
    projectId: 'crm-system-db',
    authDomain: 'crm-system-db.firebaseapp.com',
    databaseURL:
        'https://crm-system-db-default-rtdb.firebaseio.com',
    storageBucket: 'crm-system-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqu90BBmiHI9oJoY3psfLV-YMAxhb9Hs',
    appId: '1:879415072254:android:985015fb00d40117495caf',
    messagingSenderId: '879415072254',
    projectId: 'crm-system-db',
    storageBucket: 'crm-system-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc9k9kcOx_7Pn-u8TPuMSCapgbQeTHCeo',
    appId: '1:879415072254:ios:5a54ea138c4a7d27495caf',
    messagingSenderId: '879415072254',
    projectId: 'crm-system-db',
    storageBucket: 'crm-system-db.firebasestorage.app',
    iosBundleId: 'com.example.crmSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc9k9kcOx_7Pn-u8TPuMSCapgbQeTHCeo',
    appId: '1:879415072254:ios:5a54ea138c4a7d27495caf',
    messagingSenderId: '879415072254',
    projectId: 'crm-system-db',
    storageBucket: 'crm-system-db.firebasestorage.app',
    iosBundleId: 'com.example.crmSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjMahvKt4NNSqSQ2vWgl3JM4lWkhCAhZI',
    appId: '1:879415072254:web:1c2ce944b071710c495caf',
    messagingSenderId: '879415072254',
    projectId: 'crm-system-db',
    authDomain: 'crm-system-db.firebaseapp.com',
    storageBucket: 'crm-system-db.firebasestorage.app',
  );
}
